"""optimize indexes: composite index for ticker+timestamp

Revision ID: bc1eb3694e77
Revises: 8526a137a5b4
Create Date: 2026-01-20 15:49:04.397062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1eb3694e77'
down_revision: Union[str, None] = '8526a137a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker', table_name='prices')
    op.drop_index('ix_prices_timestamp', table_name='prices')
    op.create_index('ix_prices_ticker_timestamp', 'prices', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker_timestamp', table_name='prices')
    op.create_index('ix_prices_timestamp', 'prices', ['timestamp'], unique=False)
    op.create_index('ix_prices_ticker', 'prices', ['ticker'], unique=False)
    # ### end Alembic commands ###
